# ======================================================================================
#                             WELCOME TO THE CONFIG
#                                      FOR
#                                 MODERN ECONOMY
# ======================================================================================
# NOTE: BOT_TOKEN & MONGO CLIENT DETAILS ARE STORED IN THE .env FILE!
# The prefix for the bots commands
Prefix: "!"

# Set what the bot is currently playing
bot_status_text: "[!] | Modern Economy"

# IDLE, DND, ONLINE, OFFLINE
bot_activity: online

# The ID of the user who owns this bot (In most cases, that'll be you)
bot_owner_id: 512760269764820993

# Disable / Enable the bot from sending the private message when joining a guild (True/False)
private_message: True


# ======================================================================================
#                                     MONEY
# ======================================================================================
# How much money a user will earn when they get added to the database
starting_money: 100

# Currency Type (e.g $100)
currency_type: $

# How much money the user should receive from the Daily Command
daily: 100

# ======================================================================================
#                                     GAMBLING
# ======================================================================================

# The cap of how much money a user can bet on HIGH/LOW
high_low_cap: 3000

# The cap of how much money a user can bet on BLACK/RED
black_red_cap: 25000

# The cap of how much money a user can bet on SLOTS
slots_cap: 100000

# ======================================================================================
#                                   SHOPS
# ======================================================================================

# The item being sold in the shop
items: ["Stock", "Computer", "Fishing Rod", "Ide License", "Server", "Leash"]

# The price of the item
prices: [1000, 100000, 500, 30000, 25000, 250]

# The description of the item
description: ["Required for **Shop Owner**", "Required for **Programmer**", "Required for **Fisher**", "Required for **Programmer**", "Required for **Programmer**", "Required for **Dog Walker**"]

# ======================================================================================
#                                   JOBS
# ======================================================================================

# The starting daily income for 'Shop' Job
starting_shop_income: 1000

# How much money a user needs to start a Shop Job
shop_money_requirement: 1000

# The starting daily income for 'Fisher' Job
starting_fisher_income: 600

# How much money a user needs to start a Fisher Job
fisher_money_requirement: 600

# The starting daily income for 'Programmer' Job
starting_programmer_income: 10000

# How much money a user needs to start a Programmer Job
programmer_money_requirement: 10000

# The starting daily income for 'Dog Walker' Job
starting_dog_income: 50

# How much money a user needs to start a Dog Walker Job
dog_money_requirement: 50

# ======================================================================================
#                                  LEADERBOARD
# ======================================================================================
# Amount of users to be shown on the leaderboard
leaderboard_amount: 10

# Sets aliases for the leaderboard command
leaderboard_alias: ['lb', 'leader', 'rankings', 'baltop']


# ======================================================================================
#                                   EMBED
# ======================================================================================
# Leaderboard Embed Colour | Must Be Hex Notation (Replace # with 0x)
leaderboard_embed_colour: 0xffffff

# Embed Colour | Must Be Hex Notation
embed_colour: 0xffffff

# Error Embed Colour | Must Be Hex Notation
error_embed_colour: 0xFF7F7F

# Success Embed Colour | Must Be Hex Notation
success_embed_colour: 0x32CD32


# ======================================================================================
#                                     HELP
# ======================================================================================
help_command: True


# ======================================================================================
#                                    THE END
# ======================================================================================